cilium:
  hubble:
    ui:
      enabled: true
    relay:
      enabled: true
    metrics:
      enabled: ~
  kubeProxyReplacement: true
  enableNodePort: true
  lbExternalClusterIP: true
  monitor:
    enabled: true
  l2announcements:
    enable: true
  dashboards:
    enabled: true
    label: grafana_dashboard
  operator:
    dashboards:
      enabled: true
    prometheus:
      enabled: true
    #   port: 9963
    #   serviceMonitor:
    #     enabled: true
  serviceMonitor:
    enabled: true
  gatewayAPI:
    enabled: true
    # hostNetwork:
    #   enabled: true
    #   nodes:
    #     matchLabels:
    #       node-role.kubernetes.io/control-plane: ""

#https://github.com/cilium/cilium/blob/v1.18.3/install/kubernetes/cilium/values.yaml
