cilium:
  # authentication:
  #   enabled: true
  # loadBalancer:
  #   algorithm: maglev
  lbipam:
    enabled: true
  # encryption:
  #   enabled: true
  #   type: wireguard
  #   nodeEncryption: true
  # routingMode: native
  ipv4-native-routing-cidr: "192.168.0.0/24"
  enable-ipv4: true
  enable-ipv4-masquerade: true
  enable-ip-masq-agent: false
  # ipam: "bare-metal-pool"
  envoy:
    enabled: true
  metrics:
    enabled:
      - prometheus
  hubble:
    ui:
      enabled: true
    relay:
      enabled: true
    metrics:
      enabled:
        - dns
        - drop
        - tcp
        - flow
        - port-distribution
        - icmp
        - httpV2:exemplars=true
    enableOpenMetrics: true
  kubeProxyReplacement: true
  enableNodePort: true
  lbExternalClusterIP: true
  monitor:
    enabled: true
  l2announcements:
    enable: true
  dashboards:
    enabled: true
    label: grafana_dashboard
  operator:
    dashboards:
      enabled: true
    prometheus:
      enabled: true
      port: 9963
      serviceMonitor:
        enabled: true
        labels:
          release: monitoring
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      labels:
        release: monitoring
  gatewayAPI:
    enabled: true
    hostNetwork:
      enabled: true
      ports:
        https: 443
    serviceType: ClusterIP

    #serviceType: "LoadBalancer"
    #externalTrafficPolicy: Local
      # nodes:
      #   matchLabels:
      #     node-role.kubernetes.io/control-plane: ""

#https://github.com/cilium/cilium/blob/v1.18.3/install/kubernetes/cilium/values.yaml
