cilium:
  hubble:
    ui:
      enabled: true
    relay:
      enabled: true
  kubeProxyReplacement: true
  enableNodePort: true
  monitor:
    enabled: true
  l2announcements:
    enable: true
  dashboards:
    enabled: false
    label: grafana_dashboard
  enabled: false
  gatewayAPI:
    enabled: true
    hostNetwork:
      enabled: true
      nodes:
        matchLabels:
          node-role.kubernetes.io/control-plane: ""
