###replaced by Cilium Gateway API


# ingress-nginx:
#   controller:
#     service:
#       type: ClusterIP
#       externalIPs:
#       - 192.168.0.202
#     replicaCount: 2
#   #   replicas: 2
#   # replicaCount: 2
#   # replicas: 2
