headlamp:
  config:
    kubeConfigPath: ""
    clusterName: "local"
    args:
      - "-allow-all-namespaces"
    oidc:
      secret:
        create: false
  clusterRoleBinding:
    create: true
  serviceAccount:
    create: true
    name: "headlamp"
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  pluginsManager:
    enabled: true
    resources:
      requests:
        cpu: "100m"
        memory: "1024Mi"
      limits:
        memory: "4Gi"
