headlamp:
  env:
    - name: KUBERNETES_SERVICE_HOST
      value: "localhost"
    - name: KUBERNETES_SERVICE_PORT
      value: "6443"
  config:
    clusterName: "local"
    args:
      - "-allow-all-namespaces"
      - "-log-level=debug"
    oidc:
      secret:
        create: false
  clusterRoleBinding:
    create: true
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  pluginsManager:
    enabled: false
    resources:
      requests:
        cpu: "100m"
        memory: "1024Mi"
      limits:
        memory: "4Gi"
    # env:
    #   - name: HTTPS_PROXY
    #     value: ""
  # env:
  #   - name: KUBERNETES_SERVICE_HOST
  #     value: "192.168.0.202"
  #   - name: KUBERNETES_SERVICE_PORT
  #     value: "6443"
