headlamp:
  httpRoute:
    enabled: true
    hostnames:
      - dashboard-salaserver.linuxadmin.eu
    # parentRefs:
    #   - group: gateway.networking.k8s.io
    #     kind: Gateway
    #     name: cilium-gateway-https
    #     namespace: kube-system
  config:
    kubeConfigPath: ""
    clusterName: "local"
    args:
      - "-allow-all-namespaces"
    oidc:
      secret:
        create: false
  clusterRoleBinding:
    create: true
  serviceAccount:
    create: true
    name: "headlamp"
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  pluginsManager:
    enabled: true
    resources:
      requests:
        cpu: "100m"
        memory: "1024Mi"
      limits:
        memory: "4Gi"
